game_project_game:
    resource: "@GameProjectGameBundle/Resources/config/routing.yml"
    prefix:   /

game_project_user:
    resource: "@GameProjectUserBundle/Resources/config/routing.yml"
    prefix:   /

game_project_admin:
    resource: "@GameProjectAdminBundle/Resources/config/routing.yml"
    prefix:   /

