GameProject\GameBundle\Entity\GameContent:
    properties:
        name:
            - NotBlank: ~
        description:
            - NotBlank: ~
        link:
            - NotBlank: ~

GameProject\GameBundle\Entity\CategoryContent:
    properties:
        name:
            - NotBlank: ~